name: Builder

env:
  ARCHITECTURES: '["amd64", "aarch64"]'
  IMAGE_NAME: addon-powerwall3mqtt

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  init:
    name: Initialize build
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v6.0.2
        with:
          submodules: recursive

      - name: Get add-on version
        id: version
        run: |
          version=$(grep '^version:' powerwall3mqtt/config.yaml | cut -d'"' -f2)
          echo "version=${version}" >> $GITHUB_OUTPUT

      - name: Get build matrix
        id: matrix
        uses: home-assistant/builder/actions/prepare-multi-arch-matrix@2026.03.2
        with:
          architectures: ${{ env.ARCHITECTURES }}
          image-name: ${{ env.IMAGE_NAME }}

  build:
    name: Build ${{ matrix.arch }} image
    needs: init
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      id-token: write
      packages: write
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.init.outputs.matrix) }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v6.0.2
        with:
          submodules: recursive

      - name: Build image
        uses: home-assistant/builder/actions/build-image@2026.03.2
        with:
          arch: ${{ matrix.arch }}
          context: ./powerwall3mqtt
          container-registry-password: ${{ secrets.GITHUB_TOKEN }}
          image: ${{ matrix.image }}
          image-tags: |
            ${{ needs.init.outputs.version }}
            latest
          push: ${{ github.event_name != 'pull_request' }}
          version: ${{ needs.init.outputs.version }}

  manifest:
    name: Publish multi-arch manifest
    needs: [init, build]
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    permissions:
      id-token: write
      packages: write
    steps:
      - name: Publish multi-arch manifest
        uses: home-assistant/builder/actions/publish-multi-arch-manifest@2026.03.2
        with:
          architectures: ${{ env.ARCHITECTURES }}
          container-registry-password: ${{ secrets.GITHUB_TOKEN }}
          image-name: ${{ env.IMAGE_NAME }}
          image-tags: |
            ${{ needs.init.outputs.version }}
            latest
